### ISSUE TITLE
Add support for or doucment approach taken for "record type" glyphs...

### ISSUE THREAD

**Issue by afarlie** [psb1558/Junicode-New#1]
Specifically those used in   https://archive.org/details/recordinterpret00mart/page/n11/mode/2up and which per wikipedia  https://en.wikipedia.org/wiki/Record_type  was also used for certain offiical reproductions of older manuscripts.  (Such as the Statutes of the Realm. - https://babel.hathitrust.org/cgi/pt?id=pst.000017915496&view=1up&seq=68)

Having appropriate support for this represntation would be useful...

**Comment by psb1558** [comment]
I'll go through the Record Interpreter carefully when I have time, but on first glance I don't see anything that's not already covered in Unicode/[MUFI](https://skaldic.abdn.ac.uk/m.php?p=mufi)/Junicode, either via precomposed characters or combining marks. (I noticed a lot of instances of f with a high bar, and I've added an anchor to handle that case.)

**Comment by afarlie** [comment]
That's good to hear..  

Then my 'feature' request would be for a documentation chart, which would explain how the 'record-type' characters (in the book I mentioned) can be mapped with combining marks, and existing characters. 

The other character which I think is already supported is Yogh, https://en.wikipedia.org/wiki/Yogh#List_of_Middle_English_words_containing_a_yogh. (It's not necessarily present in English but is in some older Scots text, I'm told.)

**Comment by psb1558** [comment]
As the set of symbols is relatively small, I'll produce a little guide.

Some of the abbreviation marks look rather different from those in Junicode, but still recognizable: Junicode is not for making facsimiles of either MSS or printed books. However, I have added a variant of U+A75D, "LATIN SMALL LETTER RUM ROTUNDA," since it is different enough from these 19th c. books to cause confusion. It is available via OpenType feature cv60.
<img width="112" alt="image" src="https://user-images.githubusercontent.com/16215767/81568405-b96e0380-936b-11ea-843e-c94f9adefb2b.png">
It should show up in the character palette in InDesign and other Adobe apps. I doubt you can get at it in MS Word, for which the OpenType support is feeble.

**Comment by afarlie** [comment]
And thank you for the hint about what the glyph should be, it means I can use the appropriate codepoint and apply the character variant as you suggest.  (My intended usage was on Wikisource to eventually transcribe the book in question.)

I will assume that the above cv60  applies to JuniusX, as opposed to the Junicode legacy version, I will consider raising a ticket on the Wikimedia Phabricator to get the new font version supported there.)  

Thank you again for considering a documentation/typesetting guide :).

**Comment by jsbien** [comment]
I've made a git pull, but otfinfo -f fonts/JuniusX-Regular.ttf doesn't show cv60. Am I doing something wrong?

**Comment by psb1558** [comment]
No, I just haven't updated the repository yet. Will do it when I have the ital and the new dashes done. An hour or so.

**Comment by afarlie** [comment]
The other variant or new charcter I would suggest considering placing is one that distinguishes  the abbreviation marking for ER,IR,RE  from a rotunda r (A75A). (The positioning of that symbol in the code chart suggested to me that it's intended for that abbreviation)  In the works I linked initally this ER marking seems to have 2 versions, one that's plain and one that's added as flourish(?) on other letters like p c v etc.. 
(Aside: Would it be advised also to have a way of supporting these abbreivation forms by means of an 'scribabbrv' option which would collapse them from per/cer/ver/rum/tum etc. as typed? )
Thanks again for the updates...

**Comment by psb1558** [comment]
New version with rumrotunda.alt now in the repository.

**Comment by psb1558** [comment]
I have dropped a file "Record_Interpreter_notes.pdf" into the repository. Not a nice clean grid, but a series of notes--but it covers the whole thing, I think. Look it over, and if you have questions or concerns then, I'll address them.

**Comment by afarlie** [comment]
Thank you very much indeed.  That will let me write up some suitable template code at Wikisource for my attempted transcription efforts when I start on them at the start of June.

I don't use Adobe (no subscription), I'll see if Scribus (https://www.scribus.net/downloads/stable-branch/) has the appropriate typeface support.

**Comment by psb1558** [comment]
I'm pretty sure Scribus doesn't (I check up on it now and then). But you can test in a browser (they all have better OpenType support than any desktop application but LibreOffice) by visiting https://psb1558.github.io/Junicode-New/ and typing in the box.

**Comment by jsbien** [comment]
On Mon, May 11 2020 at 16:37 -07, Peter Baker wrote:
> I'm pretty sure Scribus doesn't (I check up on it now and then).

XeLaTeX has no problem with the character.

> But you can test in a browser (they all have better OpenType support than any desktop
> application but LibreOffice) by visiting https://psb1558.github.io/Junicode-New/ and typing in the box.

Is this really that simple? How to access and switch on the appropriate
feature?

**Comment by jsbien** [comment]
Off the primary topic: consider using [Transkribus](https://Transkribus.eu) for the transcription and then converting the output to whatever you wish.

**Comment by psb1558** [comment]
Oh, right. I haven't activated cv tags on that web page. But it lets you play with much else. For testing, I suggest LibreOffice writer. It's free, and it uses the extremely competent Harfbuzz layout engine--the same used by Firefox and Chrome.

I ran into a significant problem with combining marks and Harfbuzz: it does not treat combining marks encoded in the Private Use Area as combining marks, and so it does not position them properly over base glyphs. I doubt this is a bug: rather it is an efficiency.

My workaround is to provide unencoded duplicates of the MUFI combining marks and make them accessible via the "cvNN" OpenType feature. This is explained in detail in the document "Diacritics_guide.pdf," which I have dropped into the repository. The current version of the roman font (uploaded just now) contains these cvNN features.

**Comment by dscorbett** [comment]
HarfBuzz treats PUA glyphs as marks if their glyph class is specified as mark, which JuniusX does. For example, here is a PUA mark on a narrow and a wide base, to show that mark attachment works:
![IW](https://user-images.githubusercontent.com/1124347/81691636-24cada80-942b-11ea-9e6a-35f9cd0de4c4.png)
I got that image using HarfBuzz’s hb-view utility. However, it does look wrong in LibreOffice, Firefox, and Chrome. Maybe each of those has a bug in its script itemizer, or maybe there is a subtle bug in HarfBuzz that doesn’t manifest via hb-view. In any case, failing to position PUA marks is definitely a bug, not a legitimate strategy for efficiency.

**Comment by psb1558** [comment]
Thanks for this, David. I'll open an issue on Harfbuzz and see what they have to say.

**Comment by psb1558** [comment]
BTW MS Word is also having trouble with MUFI diacritics:
<img width="249" alt="image" src="https://user-images.githubusercontent.com/16215767/81709371-d116bc00-943f-11ea-97c1-135d4e166861.png">
I believe I remember reading that Harfbuzz is supposed to be functionally the same as the layout engine from MIcrosoft.

**Comment by dscorbett** [comment]
HarfBuzz is supposed to be compatible with Microsoft’s shaping engine, except in some cases where the latter has a clear bug.

**Comment by psb1558** [comment]
Interesting and informative exchange with the Harfbuzz folks ([](https://github.com/harfbuzz/harfbuzz/issues/2401)), the upshot of which is that the problem of combining diacritics in the PUA is not going to be fixed anytime soon, as it involves not Harfbuzz itself, but the way apps chop text up into runs before it gets to Harfbuzz.

I have given up my scheme of using cvNN tags, which no one will ever learn, and instead am using mnemonic codes of 1-4 letters enclosed in {^..}, like {^a} for combining a, {^aopn} for combining open a. It's a variant of a scheme I tried out in Elstob. I'll write up a doc to replace the one I wrote earlier today.

**Comment by afarlie** [comment]
Elstob was using 'glyph' compostion  (gcmp, ccmp) a feature supported in Opentype? 

If so I will open a new issue, regarding some thoughts I have on this..

**Comment by psb1558** [comment]
Yes, ccmp, experimentally. The idea was that, by doing it very early in the process, the character introduced that way becomes subject to all the other features. Also, because ccmp is (or should be) always on, users don't have the hassle of having to turn on a feature to use it. Possible downsides: a performance hit, and of course certain character sequences become unusable for other purposes—that's why I chose the hopefully unlikely trigger {()}. I'll post JuniusX with a similar feature shortly. See what you think.

**Comment by psb1558** [comment]
This one seems finished. Reopen if any issues arise around the "Record Interpreter."

**Comment by dscorbett** [comment]
FYI, [the itemization bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1637405) has been fixed in version 78, so private-use diacritics will work in Firefox.

**Comment by psb1558** [comment]
Amazing! I didn't expect that at all, let alone so quickly. Now if other apps would make the same fix ...

**Comment by jsbien** [comment]
Record Interpreter Notes do not mention that the zigzak is used also over n, e.g. on page vi. Perhaps it is worth adding?

**Comment by psb1558** [comment]
Thanks, I've done this.
