### ISSUE TITLE
Slashed Zero - additional replacements

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-New#12]
The Slashed Zero (zero) feature current only replaces the `zero` and `zero.osf`.
Current
```
lookup SingleSubstitution8 {
  sub zero -> zero.zero;
  sub zero.osf -> zero.osf.zero;
}
```
Missing: 	
Subscript zero - uni2080 -> uni2080.zero
Superscript zero - uni2070 -> uni2070.zero
Subscript zero oldstyle - zero.subold -> zero.subold.zero
Superscript zero oldstyle - zero.supold -> zero.supold.zero

Updated
```
lookup SingleSubstitution8 {
  sub zero -> zero.zero;
  sub zero.osf -> zero.osf.zero;
  sub uni2080 -> uni2080.zero;
  sub uni2070 -> uni2070.zero;
  sub zero.subold -> zero.subold.zero;
  sub zero.supold -> zero.supold.zero;
}
```
I assumed that since the other `.zero` replacements exist that this is planned.
Please advise.

**Comment by psb1558** [comment]
I should absolutely have these additional glyphs. Plus additional figures to fill out the usual quartet of oldstyle/lining and proportional/tabular. I'll leave this issue open till I can get around to these things.

**Comment by kenmcd** [comment]
Those four glyphs are already there.
That is how I across this issue.
Just the OpenType script needs to be changed to add these replacements.

**Comment by psb1558** [comment]
I'll be darned. I've fixed this in the roman. Still need to add the necessary glyphs for italic.

**Comment by kenmcd** [comment]
This was not working 100% so I analyzed all the types of figures and the slashed zero feature.
Below is and image and a PDF of the analysis.
I have highlighted issue in yellow.

First, the **Proportional Lining** figures are not proportional, they are fixed width just like the default **Tabular Lining** figures.

**Proportional Lining** - the slashed zero is named `zero.zero.lf` and should be `zero.lf.zero` 
This slashed zero is missing from the feature code.
So I added: `sub zero.lf -> zero.lf.zero;`  (see full code below)

**Tabular Oldstyle** (onum) - the slashed zero code is missing from the feature code.
So I added: `sub zero.tosf -> zero.tosf.zero;`

**Superscript Tabular** - I highlighted the character names only because of the inconsistent naming.

After renaming the character above to `zero.lf.zero` the new Slashed Zero code is:

`
lookup SingleSubstitution11 {   
  sub zero -> zero.zero;   
  sub zero.lf -> zero.lf.zero;
  sub zero.osf -> zero.osf.zero;
  sub zero.subold -> zero.subold.zero;
  sub zero.supold -> zero.supold.zero;
  sub zero.tosf -> zero.tosf.zero;
  sub uni2080 -> uni2080.zero;
  sub uni2070 -> uni2070.zero;
}`

**Comment by psb1558** [comment]
The proportional lining and tabular oldstyle figures are new and unfinished. I'll get back to them when I've finished the small caps (only about thirty left!).

**Comment by kenmcd** [comment]
Ahhh ... so I have again gotten ahead of the work-in-progress.
Sorry if it is making you crazy.

But, if you could please make the two relatively easier fixes below it would help.
That way as I am working on the figures in the Specimens and the OpenType Feature Reference I can confirm that things are all _working_ properly, and then when the proportional figures are done it will all automatically _display_ properly without additional detailed testing.
I will just leave some notes to myself in the docs to check the display later.

1. Rename `zero.zero.lf` to `zero.lf.zero` 
2. Update the Slashed Zero OpenType code to:
```
lookup SingleSubstitution11 {
  sub zero -> zero.zero;
  sub zero.lf -> zero.lf.zero;
  sub zero.osf -> zero.osf.zero;
  sub zero.subold -> zero.subold.zero;
  sub zero.supold -> zero.supold.zero;
  sub zero.tosf -> zero.tosf.zero;
  sub uni2080 -> uni2080.zero;
  sub uni2070 -> uni2070.zero;
}
```
Thanks!

**Comment by psb1558** [comment]
It's good to bring these things up, because you have no way of knowing whether you're seeing a bug or a thing that's been taken apart and not yet put back together. If I can't get to a thing right away, the issue can sit here as a reminder. In any case, I appreciate the input from both you and Janusz.

I am a gruff old man, and somewhat overwhelmed by the scale of the task I have taken on.

There are still 100,000 things, large and small, to see to, but the (roman) font is in a surprisingly good place: all of 3500+ glyphs with four compatible masters, so that one can generate 15 static ttf fonts of reasonable quality or a variable font that (astonishingly) actually works.

I've made these changes to the OT code and will generate fonts and post them and the source. Then, alas, I have to spend the day grading for my summer course.

**Comment by kenmcd** [comment]
> I've made these changes to the OT code and will generate fonts and post them and the source.

Slashed Zero feature all working now!
