### ISSUE TITLE
Another variant of e with ogonek

### ISSUE THREAD

**Issue by jsbien** [psb1558/Junicode-New#13]
Before a variant of e caudata became generally used for a nasal sound in Polish, e with stroke was used instead.  In a diachronic [IMPACT corpus](https://ispan.waw.pl/journals/index.php/cs-ec/article/view/cs.2014.008) e with stroke has about [25000 occurences](http://bc.klf.uw.edu.pl/289/) (while e with ogonek has about 40000). In the corpus the character was represented respectively by LATIN SMALL/CAPITAL LETTER E WITH STROKE (U+0246 and U+0247), so it
can be considered a glyph variant of this codepoint; however using U+0246 and U+0247 is not a generally accepted standard, so treating it as just another variant of e with ogonek seems OK.
![JSB00434985ksi1](https://user-images.githubusercontent.com/8024702/83328602-77f2b900-a284-11ea-9e05-32ed9196bbaf.png)

**Comment by psb1558** [comment]
As with the variants of ą,do you have any images of the capital of this variant?

**Comment by jsbien** [comment]
![NT1Estroke](https://user-images.githubusercontent.com/8024702/83329986-b2605400-a28c-11ea-9c3a-bdb6086da6b1.png)
![NT366Estroke](https://user-images.githubusercontent.com/8024702/83329988-b2f8ea80-a28c-11ea-8a16-184374f455c3.png)
![Oekonomika188Estroke](https://user-images.githubusercontent.com/8024702/83329989-b2f8ea80-a28c-11ea-84cb-151175fe6268.png)

**Comment by psb1558** [comment]
The lowercase:
<img width="285" alt="image" src="https://user-images.githubusercontent.com/16215767/83442640-7fe26280-a416-11ea-87b0-be38724506f7.png">
The model again:
<img width="288" alt="image" src="https://user-images.githubusercontent.com/16215767/83442700-98527d00-a416-11ea-8616-fa94403db807.png">

**Comment by psb1558** [comment]
BTW, what is this **v** about?
<img width="227" alt="image" src="https://user-images.githubusercontent.com/16215767/83442791-c1730d80-a416-11ea-9f5d-0199aed2d660.png">

**Comment by psb1558** [comment]
Is this variant shape of ogonek needed for any of these?
<img width="548" alt="image" src="https://user-images.githubusercontent.com/16215767/83452103-1f5b2180-a426-11ea-8b5d-dda7efa56698.png">

**Comment by psb1558** [comment]
The caps:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/16215767/83465890-660b4480-a443-11ea-8663-189ecc655296.png">

**Comment by jsbien** [comment]
On Mon, Jun 01 2020 at 11:47 -07, Peter Baker wrote:
> BTW, what is this v about?

No idea, never noticed it before and I'm not aware of any other
occurence. There seems to be no difference in the meaning.

On Mon, Jun 01 2020 at 13:37 -07, Peter Baker wrote:
> Is this variant shape of ogonek needed for any of these?

No

On Mon, Jun 01 2020 at 17:07 -07, Peter Baker wrote:
> The caps:

OK

**Comment by psb1558** [comment]
Italic
<img width="161" alt="image" src="https://user-images.githubusercontent.com/16215767/83693674-8d3d4f80-a5c4-11ea-8513-be98f108617d.png">
The lc is after this:
<img width="81" alt="image" src="https://user-images.githubusercontent.com/16215767/83693746-ab0ab480-a5c4-11ea-9a0c-a486cccd16cc.png">

**Comment by jsbien** [comment]
Personally I would prefer the stroke in the capital letters slightly moved to the right (also in roman version, forgot to mention earlier), but I don't attach much importance to such details.

**Comment by psb1558** [comment]
It's an interesting design problem. The old punch cutters mostly seem to have wanted a long, plainly visible stroke, but there was a danger of collision with the vertical serif of the middle bar of E. In one of your models the "ogonek" stroke is shortened so it can be centered without a collision. In one of them it's moved to the left (this is the model I followed). And in one the angle is sharply increased so that the stroke can end up to the right of that serif. I'll work on this--but it has still got to be one of those three options, I think.

**Comment by jsbien** [comment]
OK

**Comment by psb1558** [comment]
This one takes the approach of a long and dramatically angled (about 40°) stroke that traverses nearly the whole width of the character.
<img width="86" alt="image" src="https://user-images.githubusercontent.com/16215767/83863852-ece54900-a6f1-11ea-8d43-b88dde94d669.png"> 
![image](https://user-images.githubusercontent.com/16215767/83863883-fa023800-a6f1-11ea-89a2-4192c3246b39.png)

**Comment by psb1558** [comment]
The same approach in italic.
<img width="89" alt="image" src="https://user-images.githubusercontent.com/16215767/83865168-cfb17a00-a6f3-11ea-9a26-c7f6d43690cc.png">

**Comment by jsbien** [comment]
Look very nice for me.
