### ISSUE TITLE
ss07 Underdotted uses fleurons as before characters

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-New#15]
When documenting **ss07- Underdotted** I noticed that the last 10 _before_ characters are fleurons.

![JuniusX_User_Guide_ss07_Underdotted_uses_Fleurons](https://user-images.githubusercontent.com/844920/83350890-1b2ee700-a2f4-11ea-95a4-7ef55a0c2719.png)

Is this intended to work like this?
Or is this an accident which needs to be changed?
Just seemed a bit odd.

I double-checked the OpenType code and the codepoints and that is what is there.

**Comment by psb1558** [comment]
Must be bitrot. I'll check it out.

**Comment by psb1558** [comment]
I see what happened. When chars were added to Unicode and old MUFI PUA slots were decomissioned, I used those slots for fleurons, but forgot to change the feature code. I'm glad you're catching these errors, @kenmcd !

**Comment by kenmcd** [comment]
Looks like the Fleurons are in a location intended for
I am looking at _MUFI character recommendation  ※  Part 2: code chart order_, 
page 124 - Subrange 16: Characters with acute accent
and it has those characters in that range.

**Comment by kenmcd** [comment]
> I'm glad you're catching these errors, @kenmcd !

Expect more.
I have found in other documentation projects I have done that when you document every single feature down to the last detail you find some stuff that is not working exactly as expected.
But that is a good thing. :-)

**Comment by psb1558** [comment]
No, those notes about decomposition are reflecting the decommissioned slots, e.g. U+A732 used to be U+EF90, etc. It's so hard to keep a large complex document like the (printable) MUFI spec up to date! Should generally prefer the [online spec](https://skaldic.abdn.ac.uk/m.php?p=mufi).

**Comment by jsbien** [comment]
As for MUFI online specification, are you aware of
http://www.kreativekorp.com/charset/PUADATA/PUBLIC/MUFI/
?

**Comment by psb1558** [comment]
I haven't see that before. Pretty cool, but it doesn't seem to be correcting errors, e.g.

`EFE0;LATIN CAPITAL LIGATURE AA WITH ACUTE;Lu;0;L;<compat> EF90 0301;;;;N;;;;EFE1;`

when there is no U+EF90 in MUFI. It's unfortunate that the current MUFI website doesn't seem to have decomposition data.

**Comment by jsbien** [comment]
For maintaining such data a version control system would be appropriate.

**Comment by psb1558** [comment]
True. It would make a lot of sense to maintain MUFI on Github.

**Comment by kenmcd** [comment]
ss07 is working correctly now.
