### ISSUE TITLE
Stylistic Sets draft documentation for review

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-New#16]
Attached is a PDF of the _Stylistic Sets (ss01-ss20)_ pages for review, additions, and suggestions.

Please review and make suggestions on the short descriptions to make sure they are correct, make sense, and are complete.
Note that the longer descriptions like in the Junicode documentation will be in the Introduction section of the Guide. There I will incorporate the Thorn and Eth info you posted the other day, and the Long s and Rotunda info you posted, and the Junicode doc info which still applies.
Any longer descriptions or explanations will be greatly appreciated.
Thanks!

Updated PDF (of course I found a few things after posting the first PDF)
[JuniusX_User_Guide_Stylistic_Sets_for_Review_2020-05-31_2.pdf](https://github.com/psb1558/Junicode-New/files/4708105/JuniusX_User_Guide_Stylistic_Sets_for_Review_2020-05-31_2.pdf)

**Comment by psb1558** [comment]
Nice doc! Here are some notes for you.

[Stylistic_set_notes.pdf](https://github.com/psb1558/Junicode-New/files/4710716/Stylistic_set_notes.pdf)

**Comment by kenmcd** [comment]
> 
> Nice doc! Here are some notes for you.
> 
Excellent notes! 
Really helpful info for me, and other users, to understand how the features work.
I will get those additions and changes incorporated.
:-)
