### ISSUE TITLE
Should ss01 be named Nordic thorn and eth

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-New#17]
Should 
**ss01 - Nordic letter forms**
be named
**ss01 - Nordic thorn and eth**
to match
**ss20 - English thorn and eth**

They are two sides of the same issue.
I think that would be more clear to users if the names reflect that.

Or should ss20 be named
**ss20 - English letter forms** ?

Or is there a reason for them to stay as-is?

**Comment by psb1558** [comment]
Yes, "Nordic thorn and eth." I've made the change, but it may be a while before the compiled font gets posted. This is looking to be a very busy week.

**Comment by kenmcd** [comment]
OK. Thanks. I updated the docs.
