### ISSUE TITLE
Source and/or link for Linguarum vett. septentrionalium ...

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-New#18]
In the Junicode documentation you mention that the design of Junicode is based on scans of George Hickes, _Linguarum vett. septentrionalium thesaurus grammatico-criticus et archaeologicus._

I would like to provide some images and a link to this document in the JuniusX documentation to provide some historical context.

A search of Internet Archive returned several results:
[https://archive.org/search.php?query=Linguarum%20septentrionalium](https://archive.org/search.php?query=Linguarum%20septentrionalium)

My first choice would be this one:
_Linguarum veterum septentrionalium thesaurus grammatico-criticus et archaeologicus_
[https://archive.org/details/b30454736_0001/page/n7/mode/2up](https://archive.org/details/b30454736_0001/page/n7/mode/2up)

But I really do not know what I am looking at ...

So which would you recommend?
Or is there a better option somewhere else?
I would like to provide a link so interested users could download the document.

Also, is the original document used for the scans available?

Thanks!

**Comment by psb1558** [comment]
Your second link is the one. It's the ordinary text font for vol. 1. It's a pica, I think (vol. 2, Wanley's Catalogue, is in a smaller type). They're not bad images: you can zoom fairly close to get a good look at the font.

I have a copy of the book, and I imagine I must have put it on a scanner and got the highest resolution images I could. This was in the late eighties or early nineties, mind you. It's been awhile, my memory of exactly what I did to get started is fuzzy, and those original files are long gone.

**Comment by kenmcd** [comment]
OK. Thanks. That IA version is just fine for this use.

Also I could not find:
_A Specimen of the Several Sorts of Letter Given to the University
by Dr. John Fell, Sometime Lord Bishop of Oxford. To Which Is Added
the Letter Given by Mr. F. Junius_ (Oxford, 1693)
Searches in the Internet Archive came up with nothing.

I did find a few locations of a hard copy. 
The Getty is pretty close but I assume it is not open right now.

**Comment by psb1558** [comment]
The 1706 specimen is [here](https://books.google.com/books/about/A_Specimen_of_the_Several_Sorts_of_Lette.html?id=hoNbAAAAQAAJ). The earlier printing is very hard to find. All I've ever had of it is a poor scan of one or two pages.

**Comment by kenmcd** [comment]
> 
> 
> The 1706 specimen is [here](https://books.google.com/books/about/A_Specimen_of_the_Several_Sorts_of_Lette.html?id=hoNbAAAAQAAJ). The earlier printing is very hard to find. All I've ever had of it is a poor scan of one or two pages.

Thanks.
