### ISSUE TITLE
Support two-em and three-em dash

### ISSUE THREAD

**Issue by marrus-sh** [psb1558/Junicode-New#2]
These characters were added in Unicode 6.1 as U+2E3A and U+2E3B and are not present in Junicode. They are helpful when preparing documents according to the Chicago Manual of Style. For more information, see: https://www.unicode.org/L2/L2010/10037-longdashes.pdf

(I realize that JuniusX is still very much a work in progress, and am mostly making this issue now so that I don't forget about it later.)

**Comment by psb1558** [comment]
These look appropriately academic. I'll add them.

**Comment by psb1558** [comment]
Done now.
