### ISSUE TITLE
Some Combining Diacritics appear off-center

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-New#20]
While documenting the mnemonics for typing in diacritics I noticed a few seem to be off-center.
The o looks fine, it is just there for comparison.

![Combining_Diacritics_off-center](https://user-images.githubusercontent.com/844920/84105991-cb74ad80-a9ce-11ea-8932-1d3a441f1a2b.png)

There are others that seem a little off.
Below is an image and a PDF of the full page (a working draft of this section).
Please ignore the current description text, that will be revised and expanded.
![JuniusX_User_Guide_Combining_Diacritical_Marks_1](https://user-images.githubusercontent.com/844920/84106150-3a520680-a9cf-11ea-99df-e9fe88fadf1d.png)

Here is a PDF of that page for closer examination:
[JuniusX_User_Guide_Combining_Diacritical_Marks_1.pdf](https://github.com/psb1558/Junicode-New/files/4749988/JuniusX_User_Guide_Combining_Diacritical_Marks_1.pdf)

Several of them appear to need some tweaking.
Update: The bad anti-aliasing/hinting in LibreOffice makes it look worse than it is.
The PDF at 300% looks mostly fine with just those few exceptions.

Update: 
Also, is there a better way to organize these?
This is the order found in the OpenType code.
For example: Lowercase, Dipthongs, Small Caps ? ? ?
Or some similar classification that makes sense to medievalists, or Junicode users?
Or is it OK as-is?

.

**Comment by psb1558** [comment]
U+1DD2 has its own anchor, offset somewhat to the right of the standard "top" anchor, so your first image is correct (only the collection of "us" anchors isn't yet complete--I need to write a script to place them).

I'm not seeing the effect with U+1DD3. What software are you using? In LibreOffice Writer (6.3.6.2 for Mac) I see this:
<img width="135" alt="image" src="https://user-images.githubusercontent.com/16215767/84138764-d5bd9880-aa1c-11ea-887b-6c5e12fc5bb5.png">

In the Elstob documentation I listed the alphabetic marks in alphabetical order (ligatures immediately following simplex characters), figuring that would make it easier for users to find what they wanted. (And JuniusX has a much larger collection of marks, so ease of finding is more of an issue.)  I grouped the other marks together in an arbitrary order.

**Comment by kenmcd** [comment]
> 
> 
> U+1DD2 has its own anchor, offset somewhat to the right of the standard "top" anchor, so your first image is correct (only the collection of "us" anchors isn't yet complete--I need to write a script to place them).

Did not know that. I now see that you explained that in the Elstob doc.
I should mention it in the JuniusX docs too.

> I'm not seeing the effect with U+1DD3. What software are you using? In LibreOffice Writer (6.3.6.2 for Mac) I see this:
> <img alt="image" width="135" src="https://user-images.githubusercontent.com/16215767/84138764-d5bd9880-aa1c-11ea-887b-6c5e12fc5bb5.png">

I am using LibreOffice 6.4.4.2 x64 on Windows 10 x64.
This appears to be a problem with the text rendering in LibreOffice (LO) on Windows.
On the Mac LO uses Core Text, the Mac text rendering engine.
In Windows LO uses Harfbuzz, and it does some odd things with OpenType rendering.
In the image below, on the left is the OpenType ccmp, on the right is direct Unicode input.
![JuniusX-Tests_Diacritic_direct_input_cropped](https://user-images.githubusercontent.com/844920/84339217-d35d5a80-ab52-11ea-9163-2668ca436a3f.png)

So this seems to be an issue with LibreOffice OpenType rendering on Windows.

**Comment by khaledhosny** [comment]
FWIW, LibreOffice uses HarfBuzz on all platforms for some time now.

**Comment by kenmcd** [comment]
> 
> FWIW, LibreOffice uses HarfBuzz on all platforms for some time now.

Then what is causing the difference?

**Comment by khaledhosny** [comment]
No idea.

**Comment by psb1558** [comment]
I can get LibreOffice on a Windows system. I'll see if I can reproduce this.
