### ISSUE TITLE
JuniusX - should it be written with small caps?

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-New#21]
I noticed on the JuniusX specimen page (https://psb1558.github.io/Junicode-New/)
that you wrote JuniusX using small caps (twice).
Is that a conscious decision to create a logotype, or just showing-off the small caps feature?

For example should I use that format in the user guide?
![JuniusX_logotype](https://user-images.githubusercontent.com/844920/84110162-362ae680-a9d9-11ea-9ee9-e19b23480e08.png)

Which do you prefer?

.

**Comment by psb1558** [comment]
I honestly don't know. I just thought "JuniusX" needed to look a little different from the rest of the headline and came up with that because it was easy to do. I'm open to suggestions as to how it should be treated.

BTW, the spacing of "JuniusX" (not small cap) shows how not-ready-for-prime-time this font is. The kerning is a mess.

**Comment by kenmcd** [comment]
> I honestly don't know. I just thought "JuniusX" needed to look a little different from the rest of the headline and came up with that because it was easy to do. I'm open to suggestions as to how it should be treated.

OK. Since this was a bit of whim and not a conscious branding decision I think it best to leave it as lowercase for now.
Perhaps we can play with the logotype idea later and include the small caps and some flurons, or ...
I or we can play with it later.
Will need good manual kerning tools (i.e. not LibreOffice). 
Perhaps an SVG from Inkscape would be good to support print and online.
I'll play with it and post if something looks usable.

> BTW, the spacing of "JuniusX" (not small cap) shows how not-ready-for-prime-time this font is. The kerning is a mess.

Yes, I noticed that right away, and went looking for the capital J kerning pairs.
And there are none!
 :-)
