### ISSUE TITLE
SS feature for early Polish?

### ISSUE THREAD

**Issue by jsbien** [psb1558/Junicode-New#24]
Please consider reserving a ss value for the characters proposed for Polish in the 15th century treatise by Parkosz which was the very first proposal of Polish spelling.
I mean literally just "reserving", actually including the characters in the font is another question.
Some time ago I've made an electronic edition of the treatise using transliteration. I've just finished a draft of a paper describing the typographical aspects of the treatise. Please have a look at it in a free moment. It's available for some time at https://www.dropbox.com/sh/7em11ja17wzv9q0/AAAWD_eDLhgonFe_wvqQuLX1a?dl=0 (later I will move it to ResearchGate and/or Zenodo).
All kinds of comments to the draft are welcomed.
Best regards - Janusz

**Comment by psb1558** [comment]
This wouldn't even need a separate Stylistic Set, but rather a Polish-language block in an existing one. For example, ss02 as it stands is specific to English, but its English-specific rules could be active only when the active language is English, Polish-specific rules when the language is Polish, and so on for as many languages as required. (It's also possible to have a Polish description of the ss appear when the language is Polish.)

```
lookup Polish_Stuff {
script latn;
language PLK;
. . .
} Polish_Stuff;

lookup English_Stuff {
script latn;
language ENG;
. . .
} English_Stuff;

```

**Comment by jsbien** [comment]
Thank for the info. Of course your suggestion is quite OK for me. I was not aware of this possibility. Unfortunately I know very little about fonts (although I tried to experiment with FontForge some time ago).

**Comment by psb1558** [comment]
It's actually possible for any feature. For example, "Contextual Alternates" has different rules for handling long s depending on whether the language is English or French (the rules are too complicated to program for German).

Has anyone written about the rules old typographers followed for long s in Polish?

**Comment by jsbien** [comment]
There are several issues here.

1. I'm not aware of a written description of the old rules for long s in Polish. This of course doesn't mean it doesn't exist.
2. The Polish text which I'm most familiar with is in Latin, but the use of long s seems to me incosistent, e.g. sometimes it occurs in the final position.
3. Using the language tags is OK for me, but the question is which tag.
4. Using just PLK for Parkosz could be just "wasting" the code more needed for other purposes. Are there any other options, like extended language subtags of RFC 5646? I was unable to check this quickly with Google.

**Comment by psb1558** [comment]
In English and French the rules for long s tend to get formalized fairly late--17th and 18th centuries. Earlier, the rules can be not consistent enough to program, or it can just be scribes using long s everywhere. I do want to collect these rules where I can, but I realize it can't be done for every language.

It looks as if there's just one tag for Polish. On the other hand, I may make more room in the Stylistic Sets by moving ss17 to a cvNN, and then there would be two Stylistic Sets to use in language-specific ways.

**Comment by jsbien** [comment]
I understand the number of ss is limited to 20. Moving IPA alternate(s) to cv seems any way a good idea, as this affects a single character.

**Comment by psb1558** [comment]
I'll close this. ss09 and ss17 are unoccupied now, and can be used for language-specific substitutions.
