### ISSUE TITLE
Perhaps use pcap for x-Height Small Caps

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-New#25]
I noticed the addition of `ss09` x-Height Small Caps.
This now fills all 20 `ss` options, and you have expressed perhaps moving some `ss` features to free-up space for additional `ss` options.
Some commercial fonts use the Petite Capitals (`pcap`) feature for alternate size small caps.
One even has the larger small caps in there - which was confusing at first (with no docs).

So using `pcap` could free-up some additional Stylistic Sets space for something else. 
Usage and documentation is essentially the same either way.
Unless you have a specific reason for using `ss09` ... ?
Something to consider.

**Comment by psb1558** [comment]
Oh, cool! I'll look into that. Definitely want to prefer defined features over Stylistic Sets.

I'll also move ss17 to a cvNN, since there's only one entry there, and who knows if there will ever be more?

**Comment by psb1558** [comment]
Yes, this is exactly what pcap is for. Thanks very much!

**Comment by psb1558** [comment]
Have updated Changes_post_MUFI_4.0 wih this and other edits.

**Comment by kenmcd** [comment]
> Have updated Changes_post_MUFI_4.0 wih this and other edits.

OK. Updated docs. Please review.
![JuniusX_User_Guide_Petite_Capitals_1_cropped](https://user-images.githubusercontent.com/844920/84956600-698f0480-b0ae-11ea-9b5e-71ac7389089f.png)

**Comment by psb1558** [comment]
There were a couple of problems. pcap runs after locl, so the English eth is already substituted: I added a rule to take care of that (the result should now be U+1D06). And my petite cap thorn was too big: I've corrected it. I'll generate fonts and post them, since there are lots of accumulated changes.

**Comment by kenmcd** [comment]
OK. Great. I will be watching for the new fonts.

**Comment by psb1558** [comment]
They're up now. A little more complicated than expected because I needed to take account of the English thorn: so pcap versions of both English and Icelandic thorns. But English and Icelandic eth both produce the same pcap shape.

**Comment by kenmcd** [comment]
All appears to be working well now.

![JuniusX_User_Guide_Petite_Capitals_3_cropped](https://user-images.githubusercontent.com/844920/85084463-b562ac00-b189-11ea-9853-f8bd24b81b5b.png)
