### ISSUE TITLE
Perhaps use nalt for Enclosed Alphanumerics

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-New#26]
Many commercial fonts use Alternate Annotation Forms (`nalt`) for Enclosed Alphanumerics.
See: https://docs.microsoft.com/en-us/typography/opentype/spec/features_ko#nalt 
Some fonts are very simple and only have white 0 thru 9.
Some fonts are more complex and even have multiple alternates (sort of like cvNN).

Below is output from a JuniusX test font showing all of the white Enclosed Alphanumerics.
Also shown is a simple example of multiple alternatives using Mark Pro from FontFont.
I have seen commercial fonts with as many as four alternatives.
Below is a screenshot of the tests, and the sample OpenType code below that.
Note: I forgot the zero in the screenshot examples (it is in the code).

![JuniusX-Tests_nalt_tests_cropped](https://user-images.githubusercontent.com/844920/85452051-5a490480-b54f-11ea-94b3-a8a51ff6c226.png)

JuniusX test - simple
```
lookup latn_nalt {
  sub A -> uni24B6;
  sub B -> uni24B7;
  sub C -> uni24B8;
  sub D -> uni24B9;
  sub E -> uni24BA;
  sub F -> uni24BB;
  sub G -> uni24BC;
  sub H -> uni24BD;
  sub I -> uni24BE;
  sub J -> uni24BF;
  sub K -> uni24C0;
  sub L -> uni24C1;
  sub M -> uni24C2;
  sub N -> uni24C3;
  sub O -> uni24C4;
  sub P -> uni24C5;
  sub Q -> uni24C6;
  sub R -> uni24C7;
  sub S -> uni24C8;
  sub T -> uni24C9;
  sub U -> uni24CA;
  sub V -> uni24CB;
  sub W -> uni24CC;
  sub X -> uni24CD;
  sub Y -> uni24CE;
  sub Z -> uni24CF;
  sub a -> uni24D0;
  sub b -> uni24D1;
  sub c -> uni24D2;
  sub d -> uni24D3;
  sub e -> uni24D4;
  sub f -> uni24D5;
  sub g -> uni24D6;
  sub h -> uni24D7;
  sub i -> uni24D8;
  sub j -> uni24D9;
  sub k -> uni24DA;
  sub l -> uni24DB;
  sub m -> uni24DC;
  sub n -> uni24DD;
  sub o -> uni24DE;
  sub p -> uni24DF;
  sub q -> uni24E0;
  sub r -> uni24E1;
  sub s -> uni24E2;
  sub t -> uni24E3;
  sub u -> uni24E4;
  sub v -> uni24E5;
  sub w -> uni24E6;
  sub x -> uni24E7;
  sub y -> uni24E8;
  sub z -> uni24E9;
  sub zero -> uni24EA;
  sub one -> uni2460;
  sub two -> uni2461;
  sub three -> uni2462;
  sub four -> uni2463;
  sub five -> uni2464;
  sub six -> uni2465;
  sub seven -> uni2466;
  sub eight -> uni2467;
  sub nine -> uni2468;
}
```
Mark Pro with alternates 
```
lookup Alternate2 {
  sub zero -> [uni24EA uni24FF];
  sub one -> [uni2460 uni278A];
  sub two -> [uni2461 uni278B];
  sub three -> [uni2462 uni278C];
  sub four -> [uni2463 uni278D];
  sub five -> [uni2464 uni278E];
  sub six -> [uni2465 uni278F];
  sub seven -> [uni2466 uni2790];
  sub eight -> [uni2467 uni2791];
  sub nine -> [uni2468 uni2792];
}
```

If you are interested in using the simple example, I assume Glyphs can auto-generate this code.
If you are interested in the multiple alternates, I can put that together and test it.
Or just leave it as is in `dlig`?  
Some or all of it can be in both places.

Using `nalt` seems to be more simple and easier for users, and I will document it all.
What do you think?

**Comment by psb1558** [comment]
What a great find! I'm ashamed of myself for not having spotted it before. Thanks for the offer to code it, but it was very quick to do, and I was eager to experiment a bit to see if I could get nalt to do the two-digit circled figures. Far as I can tell, it's perfectly okay to include a type 3 (ligature) lookup in nalt. But no matter how I ordered the lookups, the single-digit lookups would get executed first, so I couldn't have, say 1 producing circled 1 while 11 produced circled 11.

So I tried out using an escape character (an underscore). That worked, and I'm curious what you'll think of it. It could be extended in various ways, e.g.

```
_11 = circled 11
=11 = reverse circled 11
-11 = 11 in parens
+11 = 11 with following period
```

Or you could have (somewhat more mnemonic here):

```
_r11 = reverse circled 11
_(11 = 11 in parens
_.11 = 11 with following period
```

Or something. Suggestions very welcome. I'll drop a test file in the docs directory and upload the current fonts.

Meanwhile, I've commented out the dlig code, which honestly I never liked much.

**Comment by psb1558** [comment]
Oddly, Glyphs doesn't auto-generate any code for nalt.

**Comment by psb1558** [comment]
Actually, this works:

lookup nalt_lig {
  sub one zero by one_zero.circled ;
  sub one.circled zero by one_zero.circled ;
} nalt_lig ;

though I'm not sure why. But no escape character is needed, if it's okay to settle for just one style of two-digit circled numbers.

**Comment by psb1558** [comment]
Another revision, and this seems to take care of everything:

1. Introduce enclosed zeros where missing
2. Let nalt take care of single-digit substitutions
3. Use rlig to combine two consecutive enclosed numbers into one two-digit enclosed number

This produces the two-digit number appropriate to the index of nalt in a way that is completely transparent to users.

**Comment by kenmcd** [comment]
Wow. Nicely done.
I have analyzed/examined/rummaged-around-in hundreds (maybe thousands) of fonts.
And have never seen the double-digit numbers handled in `nalt`.
Very cool innovation.

I do have one suggestion ...  
Move the parenthesized letters from `nalt=2` into `nalt=4` with the parenthesized numbers.
That way all the parenthesized alphanumerics are together.
See example image and PDF below.

[JuniusX_User_Guide_Alternate_Annotation_Forms_nalt_1.pdf](https://github.com/psb1558/Junicode-New/files/4842426/JuniusX_User_Guide_Alternate_Annotation_Forms_nalt_1.pdf)

![JuniusX_User_Guide_Alternate_Annotation_Forms_nalt_1_2](https://user-images.githubusercontent.com/844920/85950343-09e7f300-b911-11ea-99e8-50d30be04116.png)

Note: I did notice the repeated 6 in nalt=2 after creating the image and PDF.

**Comment by psb1558** [comment]
Yes, that would be much better. But I can't have a class with a hole in it [ a.circled ? ? a.paren ], so better to swap the numbers at 2 and 4:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/16215767/85953246-f94d7200-b93c-11ea-9d22-6b126c5ca050.png">
Glad you like the double digits. Lot of stumbling around before I hit on that.

**Comment by kenmcd** [comment]
Just realized that `nalt=4` was not going to work and was going to suggest switching `nalt=2` and `nalt=4` ... and you already figured that out. :-)
Cool.
Actually, does `nalt=3` need to be last?

I will change the docs and post it when I can test with the updated fonts (to be sure).

**Comment by psb1558** [comment]
The double circled numbers would look better as no. 5, but I'm too lazy to move them.

I'll have the new fonts up later this afternoon.

**Comment by kenmcd** [comment]
OK. Looks great and all is working properly.
Final PDF and image below.
[JuniusX_User_Guide_Alternate_Annotation_Forms_nalt.pdf](https://github.com/psb1558/Junicode-New/files/4845401/JuniusX_User_Guide_Alternate_Annotation_Forms_nalt.pdf)
![JuniusX_User_Guide_Alternate_Annotation_Forms_nalt](https://user-images.githubusercontent.com/844920/86004185-c3090480-b9c7-11ea-8f66-eb6580ddf8c2.png)

**Comment by psb1558** [comment]
It looks very good! I wonder if it's worth saying much about rlig, since it is supposed to be always on; and if rlig is not on or not working, nalt won't be available either. In MS Word you can't use nalt (as far as I know, the OpenType support in Word is still extremely primitive), but rlig is working.

BTW, I just noticed the Enclosed Alphanumeric Supplement, which has code points for the enclosed zeros I added--so I'll be adding those, but I don't believe it will break your doc. However, the Supplement adds a good bit of new stuff. Some of it (caps in parentheses, digits followed by comma) can be made entirely out of components and so should add very little to the size of the font. I'll probably add those, but I'll have to think about the other stuff.

**Comment by psb1558** [comment]
I've added caps in parentheses but decided not to include anything else from the Enclosed Alphanumeric Supplement.

**Comment by kenmcd** [comment]
Looks great.
I have added the parenthesized capitals to the docs. See below.
Something you may want to consider for your long-term-not-a-priority ToDo list ...
- Tuning the vertical alignment of the parenthesized letters and numbers, sort of like the [Case-Sensitive Forms](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#case) (`case`), but not just moving the punctuation but the characters too. I have seen this in high-end Monotype and IWATA CJK fonts which have as many as 9 alternates.
- Also adjust the character spacing/kerning to tighten-up; for example in _Numbers period_.

I know these are fine-tuning finesse stuff and you have many more pressing things to do. 
But as I said above -- perhaps add it to your long-term-not-a-priority ToDo list.
  
[JuniusX_User_Guide_Alternate_Annotation_Forms_nalt_2020-06-30.pdf](https://github.com/psb1558/Junicode-New/files/4853999/JuniusX_User_Guide_Alternate_Annotation_Forms_nalt_2020-06-30.pdf)
![JuniusX_User_Guide_Alternate_Annotation_Forms_nalt_2020-06-30](https://user-images.githubusercontent.com/844920/86167869-2714f100-bacc-11ea-9941-1a6769ddfae5.png)

**Comment by kenmcd** [comment]
> I've added caps in parentheses but decided not to include anything else from the Enclosed Alphanumeric Supplement.

With what you have added you have provided users with more coverage of Enclosed Alphanumerics than 99% of the fonts out there.
Really great.

**Comment by khaledhosny** [comment]
> Actually, this works:
> 
> ```
> lookup nalt_lig {
>   sub one zero by one_zero.circled ;
>   sub one.circled zero by one_zero.circled ;
> } nalt_lig ;
> ```
> 
> though I'm not sure why. But no escape character is needed, if it's okay to settle for just one style of two-digit circled numbers.

You might want to try https://github.com/simoncozens/crowbar for debugging OpenType layout features.

**Comment by psb1558** [comment]
I will put adjustment of spacing on the to-do list. I fixed a couple of the worst ones—(J) and (Q)—but there are more.

Thanks, @khaledhosny, for the reference to crowbar. It looks great, and I will definitely get it.

**Comment by psb1558** [comment]
I think this is done now.
