### ISSUE TITLE
Plan to tag a release?

### ISSUE THREAD

**Issue by alexmyczko** [psb1558/Junicode-New#32]
Is there such a plan? People having the old sf Junicode font, can just pick this new version, and forget/remove the old one, as far as I understand, can you confirm that?

I'm packaging the old sf version as fonts-junicode for Debian (Ubuntu/Raspbian take a copy for free (and whatever others are based on Debian), see

https://packages.debian.org/sid/fonts-junicode

and it would be great to have source only releases, with only the readme, license and glyphs, and preferably a build script, I usually use

`fontmake -g the.glyph -i -o otf`

oh and it wouldn't build with fontmake, probably to be reported to them...
```
fontmake: Error: In 'Junicode-width.glyphs' -> 'master_ufo/JuniusX.designspace' -> 'instance_ufo/JuniusX-Light.ufo': Compiling UFO failed: instance_ufo/JuniusX-Light.ufo/features.fea:64:1: Feature ss10 has not been defined
```

for completeness:
```
$ fontmake -g Junicode-Italic.glyphs -i -o otf 
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "Junicode-Italic.glyphs" file into <GSFont>
WARNING:glyphsLib.builder.components:Glyph 'uni2E4E': All components of the background layer of 'Italic' will be decomposed.
WARNING:glyphsLib.builder.components:Glyph 'uni2E4E': All components of the background layer of 'Bold Italic' will be decomposed.
WARNING:glyphsLib.builder.builders.UFOBuilder:Anchors not propagated for inexistent component uniE1AC in glyph uniEBA7
WARNING:glyphsLib.builder.builders.UFOBuilder:Anchors not propagated for inexistent component oogonek in glyph uni01ED
WARNING:glyphsLib.builder.builders.UFOBuilder:Anchors not propagated for inexistent component uniE1AC in glyph uniEBA7
INFO:fontmake.font_project:Interpolating master UFOs from designspace
fontmake: Error: In 'Junicode-Italic.glyphs' -> 'master_ufo/JuniusX-Italic.designspace': Preparing the Designspace for interpolation failed: Cannot set up glyph 'g' for interpolation: Locations must be unique.'
```

**Comment by lvcivs** [comment]
Hi, I'm not the author, but I will jump in here and say that as you can read in the readme, this is in progress and unfinished. Quote: "As of 23 May 2020, the roman face is complete (though metrics, anchors, and some features still need work), and work on the italic is about 43% complete."

Not long ago, the author mentioned that the Italic is at least a year away from completion. So it is clearly too early to tag a release and ship this.

**Comment by psb1558** [comment]
Yeah, I'm very reluctant to release without a usable italic—and italic is very far from Ready for Prime Time at this point. A year or so, as @lvcivs says.

It's worth mentioning that JuniusX/VF is not a drop-in replacement for Junicode. Though the character sets are nearly identical, the OpenType features have been thoroughly rethought. There's a lot of compatibility, but anyone with a project that relies on Junicode's OpenType features is likely to break something in migrating to JuniusX/VF. That's why I've changed the name.

**Comment by alexmyczko** [comment]
@psb1558 Ok, then the new name completely makes sense... thank you for the Junicode font, it's been a beautiful addition with such a large coverage of glyphs. I've also found Joscelyn (via github author projects) and Elstob (via reddit)... they build with fontmake, however VF support in Linux is pretty bad afaik (unless you correct me), but as normal otf fonts with all the weights it's pretty fine already.

**Comment by psb1558** [comment]
Glad you like Joscelyn and Elstob. I see what you mean about Linux and variable fonts: the Elstob specimen page doesn't work terribly well in Firefox/Linux. I suppose Linux will catch up, and TeX too, where the pace of development is, you could say, stately.

I have real doubts about the future of variable fonts in desktop apps: do you really need 2,000,000 possible permutations of either JuniusX or Elstob? But on the web they really shine. I'm not even talking about the flashy animations you see by way of demos. I use the Grade axis with a subtle animation on my instructional site, and it adds a bit of polish and avoids the annoyance of reflowing text (though I doubt that anyone consciously registers it). The site is hosted on a Linux server ...

**Comment by psb1558** [comment]
The error above is the result of my forgetting to update the aalt feature when I changed ss10 to ornm. It's fixed now.

**Comment by alexmyczko** [comment]
although several years passed, 2.x betas were tagged, i updated to the beta for debian... and the binary builds of you as i am not able to build from source anymore. just to keep you updated. and to thank you for this beauty.

**Comment by psb1558** [comment]
Sorry to be so slow: making a font is a big job, and I've got various projects going on.

What do you need to be able to build from source? Elstob has a bash script, and you just need a few Open Source font-building tools to make it work. I've got much more primitive (and so unreleaased) scripts for Junicode, but I could make a script like the one for Elstob. Or, with help, a Makefile (I produce a makefile, on average, once every fifteen years or so, and I have to relearn it every time).
