### ISSUE TITLE
Request for getting line-height reduced

### ISSUE THREAD

**Issue by PaderDesign** [psb1558/Junicode-New#34]
Hello Peter,
I tested the new JuniusX font with some of my project files. Turned out, that the line-height of JuniusX is slightly higher as it used to be in Junicode. Have you made that on purpose, or would it be possible to reduce it, so it matches the line-height we had on Junicode?
And of course an image again for comparing old and new:
![Linespacing Junicode JuniusX](https://user-images.githubusercontent.com/36140729/88741547-36757180-d140-11ea-85e4-65f210d7510c.png)

Friendly greetings

**Comment by psb1558** [comment]
The differences between Junicode and JuniusX are indeed very small, and there's no reason why they shouldn't match. I've adjusted the numbers in JuniusX, and they'll be correct next time I build the font.

The only difference, btw, was in the winAscent number (2100 vs 2070). Some applications use winAscent and winDescent to calculate default line spacing, but this is an error. When you catch them doing this, you should override (in LibreOffice, choose a "Fixed" line spacing in the Paragraph > Indents & Spacing dialog). Current versions of MS Word should use the more correct typo metrics (which are the same in Junicode and JuniusX).

**Comment by psb1558** [comment]
I guess this is done.
