### ISSUE TITLE
Design of U+2123 and U+211F

### ISSUE THREAD

**Issue by adunning** [psb1558/Junicode-New#36]
Would you consider taking the opportunity of the Junicode redesign to adjust the response abbreviation, U+211F? At the moment it does not match the style of the versicle sign, U+2123.

Here is a screenshot comparing it to Andron Scriptor and Noto. U+2123 is following the style of the former (which I think better matches your style), and U+211F the latter.

<img width="697" alt="Screenshot 2020-08-31 at 20 42 14" src="https://user-images.githubusercontent.com/1084407/91759975-74940400-ebca-11ea-8124-0a080b361756.png">

Thank you for your absolutely splendid work on this project.

**Comment by psb1558** [comment]
Is this all right (four masters: Regular, Bold, Light, Condensed)?
<img width="489" alt="image" src="https://user-images.githubusercontent.com/16215767/92312616-61997f00-ef90-11ea-91ac-762c90e2484b.png">
I think the position of the stroke on Response in Junicode (and Noto) made the interior of the R too busy and dark; and surveying other fonts, the majority position seems to favor making it cross the right leg of the R. (The majority position also favors the crook on top for both Versicle and Response. Perhaps I'll send these to a couple of priests I know and solicit their opinions.)

**Comment by psb1558** [comment]
From a missal of 1700:
<img width="677" alt="image" src="https://user-images.githubusercontent.com/16215767/92313947-77fb0700-ef9f-11ea-83ab-45347c559219.png">

**Comment by psb1558** [comment]
Another, 1690. Not a great piece of printing, but . . .
<img width="782" alt="image" src="https://user-images.githubusercontent.com/16215767/92314078-07ed8080-efa1-11ea-8574-ad545218d376.png">

**Comment by psb1558** [comment]
One more, 1721, a nice piece of printing:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/16215767/92314144-de812480-efa1-11ea-8f86-7ed7160a72fb.png">
I think it's pretty clear that in the period JuniusX belongs to stylistically, the stroke of the R in Response always crosses the tail, and does not reach the top of the letter. Otherwise it is (or can be) similar to the stroke of Versicle. This I think is the direction I'm going to go in.

**Comment by psb1558** [comment]
Another try:
<img width="671" alt="image" src="https://user-images.githubusercontent.com/16215767/92315593-be5b6080-efb5-11ea-9b52-053cc8fc3c4a.png">

**Comment by adunning** [comment]
These are excellent; thank you! If you're willing to include small-caps versions, I will certainly use them.

**Comment by psb1558** [comment]
Source and newly generated fonts are in the repository now.
<img width="288" alt="image" src="https://user-images.githubusercontent.com/16215767/92411848-7e13f380-f117-11ea-8088-2c36bc48346c.png">
Versicle and reponse look as if they ought to count as capitals, but they are symbols without case—so the small cap versions are accessible via smcp along with other symbols designed to harmonize with small caps.

**Comment by adunning** [comment]
Those are excellent. Thank you for taking such trouble with this; it's a great improvement!
