### ISSUE TITLE
U+1D24 LATIN LETTER VOICED LARYNGEAL SPIRANT is too short

### ISSUE THREAD

**Issue by dscorbett** [psb1558/Junicode-New#37]
The current glyph for U+1D24 LATIN LETTER VOICED LARYNGEAL SPIRANT is only slightly taller than x-height, but it is caps-height in the document cited in the Unicode proposal; see https://www.unicode.org/L2/L2002/02141-n2419-uralic-phonetic.pdf#page=33 and https://helda.helsinki.fi/bitstream/handle/10224/4089/sovijarvi1-24.pdf#page=12.

**Comment by psb1558** [comment]
I copied the height from Gentium, but that may have been a bad bet. SIL Doulos makes it cap height, and Brill makes it the height of an lc ascender. I suppose it's most likely to be surrounded by lc characters?

**Comment by dscorbett** [comment]
Yes, as a phonetic character it would generally be amidst lowercase letters.

**Comment by psb1558** [comment]
Here's a first try. Seems to me that Brill's approach is best, considering the typical context for this glyph.
<img width="599" alt="image" src="https://user-images.githubusercontent.com/16215767/95441579-4a9bd300-0928-11eb-812a-434c146e29f4.png">

**Comment by psb1558** [comment]
Oddly, the italic character was already tall. I actually had to scale it down a bit.
<img width="221" alt="image" src="https://user-images.githubusercontent.com/16215767/95446216-fb58a100-092d-11eb-8338-523e76a89f36.png">

**Comment by psb1558** [comment]
Italic masters:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/16215767/95516865-e27fd800-098d-11eb-9c9c-69137edf0631.png">

**Comment by psb1558** [comment]
I guess this is done.
