### ISSUE TITLE
Wrong character assigned to U+E8DF (LATIN SMALL  LIGATURE LONG S L WITH STROKE)

### ISSUE THREAD

**Issue by jsbien** [psb1558/Junicode-New#38]
I incidentally used JuniusX instead Junicode and noticed that instead of the ligature another glyph is displayed (actually I'm unable to identify it).

**Comment by psb1558** [comment]
The ligature at U+E8DF has been moved to U+E8AF: [here](https://mufi.info/m.php?p=mufiversion&v=Characters%20moved%20after%20v%204.0) and [here](https://mufi.info/m.php?p=mufiversion&v=Characters%20added%20after%20v.%204.0).

If I'd been asked, I would have strongly discouraged a move like this, which seems to have been made just so the "psalmus" signs could be lined up. It's likely to be a big pain for both font makers and users.

I haven't forgotten your Old Polish characters, btw. I'm working on italic right now, and that may be the best place to start with that particular set of characters.

**Comment by jsbien** [comment]
Thanks, I somehow missed the change. I referred to it in a paper which was just accepted, so I will mention there the change.

As for Old Polish, I'm very patient :-)
