### ISSUE TITLE
A75B (LATIN SMALL LETTER R ROTUNDA) not yet available?

### ISSUE THREAD

**Issue by jsbien** [psb1558/Junicode-New#39]
What I see looks for me like a normal 'r'.

**Comment by psb1558** [comment]
Ah, um, well. This is a bit experimental, but there are two r rotundas in JuniusX. If you enter it directly or use ``ss11``, you get the regular one, and a later rule (``calt``) will change it according to common MS usage: r rotunda after letters with rounded right sides (b, o, p, etc.), regular r everywhere else.
<img width="380" alt="image" src="https://user-images.githubusercontent.com/16215767/95659405-cb0c3080-0aee-11eb-9b1b-bb1da4e24128.png">
On the other hand, if you use ``ss16`` (either by itself or in addition to ``ss11``), you get "sticky r rotunda," which remains rotunda no matter what.
<img width="388" alt="image" src="https://user-images.githubusercontent.com/16215767/95659439-0e669f00-0aef-11eb-81f9-3f2b42265bf0.png">
The same thing applies for long s: produce it with ``ss03`` or ``hist`` and you get a rule-based distribution of the letter (in English and French, anyway: I'd like to add other languages if their rules are not too complex (as they are in German)). Apply ``ss08`` and you get "sticky long s," which doesn't change (except that it does ligate with t, h, etc.).

People have been asking for the long s feature for years, and some other academically oriented fonts have it, so I'm pretty confident about that one. My r rotunda rule is similar, but (as far as I know) new.

**Comment by dscorbett** [comment]
The purpose of U+A75B LATIN SMALL LETTER R ROTUNDA is to always look like an r rotunda, just as the purpose of U+017F LATIN SMALL LETTER LONG S is to always look like a long s. The font shouldn’t obscure the underlying text for code points intended for particular glyph variants.

**Comment by psb1558** [comment]
This is right, though it didn't occur to me when I was first coding it. The best way to go about it is to make the "sticky" behavior the default, and offer the variable behavior as an option. I'll work on this.

**Comment by jsbien** [comment]
I support this. I want to quote a single r rotunda in XeLaTeX and at present it can be achieved, ad far as I know, in a very cumbersome way.

**Comment by psb1558** [comment]
I've posted this change (for both static and variable fonts). rrotunda and longs are now invariable by default, and if you apply ss16 (for rrotunda) or ss08 (for longs) you get the variable behavior.

**Comment by jsbien** [comment]
Thanks!
