### ISSUE TITLE
A variant for U+A749?

### ISSUE THREAD

**Issue by jsbien** [psb1558/Junicode-New#4]
![l2](https://user-images.githubusercontent.com/8024702/82179515-ce541500-98de-11ea-8101-5fa4f4572003.png)
![Zaborowski_Polona_7_vel](https://user-images.githubusercontent.com/8024702/82179528-d4e28c80-98de-11ea-9a1c-270d3bca0a09.png)
The character named LATIN SMALL LETTER L WITH HIGH STROKE was proposed in [N3027](http://www.unicode.org/L2/L2005/05183-n2957-mufi.pdf) and was illustrated there by two kinds of sustantially different images. The name and the reference glyph represent only one of them. The second one was illustrated by [a book from 1460](https://www.loc.gov/item/47043559/), cf. the last letter in the first image above. It appears this very shape was quite often used in Polish, cf. the last letter in the second image.

What about adding the second glyph to the font? I guess it can find applications not only in Polish texts.

**Comment by psb1558** [comment]
Does this look right?
<img width="73" alt="image" src="https://user-images.githubusercontent.com/16215767/82214985-a5368300-98e4-11ea-8c45-2f001e04085a.png">

**Comment by psb1558** [comment]
Or with the curved stroke a little wider and less kinked:
<img width="55" alt="image" src="https://user-images.githubusercontent.com/16215767/82215698-cea3de80-98e5-11ea-8534-90c4e12ca4e8.png">

**Comment by jsbien** [comment]
![l1](https://user-images.githubusercontent.com/8024702/82215387-a46b1480-9917-11ea-9367-e542d4a35013.png)
![l3](https://user-images.githubusercontent.com/8024702/82215307-81d8fb80-9917-11ea-9395-12cf0e3c3290.png)
![Zaborowski_WBC_4_regula](https://user-images.githubusercontent.com/8024702/82215622-01ff6100-9918-11ea-8e2c-25289b05ba76.png)
![Zaborowski_Polona_7_populus](https://user-images.githubusercontent.com/8024702/82215815-3bd06780-9918-11ea-9279-2d4b515507a2.png)
Thank you very much for your quick reaction.

I upload more examples. I think the lines should just touch, not cross themselves.

**Comment by psb1558** [comment]
More like this? I don't think it's there yet: the curve needs to be tighter.
<img width="60" alt="image" src="https://user-images.githubusercontent.com/16215767/82217410-5db1f600-98e8-11ea-872e-803a02790001.png">

**Comment by jsbien** [comment]
Yes, I think so.

**Comment by psb1558** [comment]
This one is closer to one of the models. The end of the curved stroke is like a flag.
<img width="102" alt="image" src="https://user-images.githubusercontent.com/16215767/82236473-23ede900-9902-11ea-9b73-2e2d0ebf2267.png">

**Comment by jsbien** [comment]
OK

**Comment by psb1558** [comment]
The images you've posted show either the character at word-end or followed by a low character (a, u), which it overhangs. Is it ever followed by a tall character (e.g. l, d), so that I need to think about avoiding collisions?

**Comment by psb1558** [comment]
Made narrower now. Here are the masters (regular, bold, light, condensed):
<img width="223" alt="image" src="https://user-images.githubusercontent.com/16215767/82255198-3d069200-9922-11ea-8e2c-49e42d3fa34a.png">

**Comment by psb1558** [comment]
This character will be available via cv13.

**Comment by psb1558** [comment]
And the italic
<img width="222" alt="image" src="https://user-images.githubusercontent.com/16215767/82261671-7abce800-992d-11ea-9e99-eb0d871e6587.png">

**Comment by jsbien** [comment]
For me the shapes are OK. I will try to however to find some examples of usage in a different contexts, a tall character in particular.

**Comment by jsbien** [comment]
![Zaborowski_WBC_03_multum](https://user-images.githubusercontent.com/8024702/82291179-d11b3c80-99a8-11ea-94e3-96c828703242.png)
I checked about 50 occurences in a text I'm working on. It is never followed by a tall character. Once it is followed by 't', which in this text is not tall.

**Comment by psb1558** [comment]
Still, it's such a common letter, it seems best to be on the safe side, so I'm taking account of b, f, h, i, l, t, and any vowel with acute or macron.

Note that cv13 applies to l as well as U+A749, so you can't apply it to the whole text as you can (so far, anyway) with cv16.

<img width="101" alt="image" src="https://user-images.githubusercontent.com/16215767/82311759-213bd400-9994-11ea-8486-94d87c2ef1f7.png">

**Comment by jsbien** [comment]
Why cv13 applies also to l? Is this just your decision or some technical limitation? I can live with it but would like to learn more about cv features. Can you point me some documentation?

**Comment by psb1558** [comment]
The spec is [here](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#tag-cv01--cv99). I thought to group characters based on the same letter. For example, alternate eogonek, now on cv03 (used to be ss15) also affects all instances of eogonek + diacritic, enlarged eogonek, superscript eogonek.

But I guess this is actually a different case, isn't it? You would want all instances of eogonek to change together. I think I'll move the rule for U+A749 to cv59.

**Comment by jsbien** [comment]
Yes, I think it will be better.

**Comment by psb1558** [comment]
I think this one is done now. Reopen if any new issue arises.

**Comment by jsbien** [comment]
I'm unable to access the variant in XeLaTeX. Perhaps this is some stupid mistake of mine, but do I understand correctly it is at cv59=1?

**Comment by psb1558** [comment]
When I rearranged them all in alphabetical order a few months ago it ended up at cv17--the only variant on that feature (so index 1, or, I think maybe 0 with FontSpec). I think I'd better work up a little guide, since there are seventy-some OpenType features now.

**Comment by jsbien** [comment]
Thanks!
