### ISSUE TITLE
Accessing variant of e caudata (contemporary vs medieval)

### ISSUE THREAD

**Issue by jsbien** [psb1558/Junicode-New#40]
Are they still at cv03? In XeLaTeX I see no difference.

**Comment by psb1558** [comment]
It's on cv08 now. And this is my opportunity to publicize my new "Feature Reference" in the doc directory of the repository. It's quick and dirty, but complete and up to date.

For what it's worth, now that the character variant features are in alphabetical order, I don't expect them to change much, if at all. The whole list of JuniusX features seems pretty much settled now.

**Comment by jsbien** [comment]
So the variants available in Junicode as ss15 are no longer available? It's OK for me, just want to be sure.

**Comment by psb1558** [comment]
No, they've all moved to cv08, which seems more appropriate, as they required indexed lists, and people will expect to find that in a cv.

**Comment by jsbien** [comment]
OK

**Comment by psb1558** [comment]
I'd like to explain that, while this moving things around is disruptive, the aim is a more rational set of OpenType features. Junicode developed over many years in a haphazard fashion, mostly before the cv features became available, with me cramming as many features as I could into a very limited number of Stylistic Sets. The cv features allow for a better organized system which aims to provide programmatic access to all MUFI characters that can be represented as variants of Unicode standard characters. JuniusX aims to provide this kind of access while also preserving features if etexts that can easily be broken by directly inputting characters from the PUA.

Over the next month or so I'm hoping to find time to work up a CSS file and a set of XeTeX/LuaTeX commands (perhaps also Word and LibreOffice templates) to simplify accessing these features.

**Comment by jsbien** [comment]
I don't use this features intensively enough to be really affected by the disruptive changes, so it's not a problem for me. I just mention them in paper accepted for publication and I was checking it is up-to-date.
I will be glad to test XeTeX/LuaTeX commands when available.
