### ISSUE TITLE
Suggestion: more systematic filenames

### ISSUE THREAD

**Issue by loveencounterflow** [psb1558/Junicode-New#41]
Hi, I was searching for a font with a broad coverage of weights, nice-looking true italics, and, well 'accented characters' which is how I found Junicode on Font Squirrel, sourceforge.net and now here on Github. It's an amazing project, I'm already test-driving it and am looking forward to italics becoming available here (FTM I'm making do with what's available on Font Squirrel).

One thing that strikes me though is that whenever I want to try out a specific font, those *filenames* make my head spin. For example there is 

* Junicode-ItalicCondensed.ttf
* Junicode-Italic.ttf
* Junicode-RegularCondensed.ttf
* Junicode.ttf

which is quite confusing to me. Given that there are already 16 font files available now things can only become worse in this respect. May I suggest to use a very simple scheme for filenames, sth like:

`basename-weight-width-style.ttf`

such that all positions have to be filled out, always. Assuming there's `roman` or `book` or `medium`, `bold`, `semibold`, and `light` for the `weight` position, `upright` and `italic` for `style`, and `condensed`, `semicondensed`, and `regular` for `width`, that would result in filenames like

* `JuniusX-book-regular-italic.ttf`
* `JuniusX-bold-condensed-upright.ttf`

and so on which IMHO are much more grockable. Of course, 'roman' and 'regular' are somewhat fuzzy in their connotations when applied to fonts, so maybe better replaced by something clearer. Also, whether an ordering of `weight-width-style` or maybe `width-style-weight` or something else is best, I'm not sure. 

What do you think?

**Comment by psb1558** [comment]
First of all I should note that Junicode Condensed is not mine. Someone (who didn't sign their work) produced it by simply squeezing everything horizontally. As far as I'm concerned, Junicode consists of four styles, Regular, Bold, Italic, and BoldItalic (as in the "Legacy" folder on this site), and of course the filename conventions for that kind of family are well established. JuniusX, by contrast, has a proper width axis, where the widths of the characters change but the stem widths remain the same.

As for filenames, I have so far simply let the Glyphs application follow its own rules, which are broadly in line with the recommendation [here](https://silnrsi.github.io/FDBP/en-US/Font_Naming.html). That is: family name (without spaces) + hyphen + stylename (without spaces). The order for the style name is WidthWeightRoman/Italic, but in stylenames the usual practice is to elide the default stylename element (unless the whole stylename would be reduced to an empty string). Google Fonts also enforces this scheme, and appears to prefer style name elements to be selected from a standard set (e.g. always "Regular," never "Book"). See, for example, the Montserrat extended family:
<img width="260" alt="image" src="https://user-images.githubusercontent.com/16215767/100517200-0e7e3500-3157-11eb-8392-f1677170b87b.png">
I have always found both font names and filenames to be rather confusing (especially the elisions), but there seems little scope for exercising discretion.

But I am happy to have a discussion of any aspect of font names or filenames where I do have discretion.
