### ISSUE TITLE
Add encoded versions of unencoded non-MUFI characters

### ISSUE THREAD

**Issue by psb1558** [psb1558/Junicode-New#45]
Per [this discussion topic](https://github.com/psb1558/Junicode-New/discussions/44), add encoded versions of characters that do not have either Unicode or MUFI/PUA encodings. OpenType features will still produce the unencoded versions.

The first step will be to make a list of all characters that need to be encoded this way.

**Comment by psb1558** [comment]
So far. I'll put up the fonts momentarily.

These characters are unencoded when entered in the recommended way, via OpenType features, but they can also be entered via the following code points. Don't rely on this yet, since I'm sure to re-order the code points.
<img width="617" alt="image" src="https://user-images.githubusercontent.com/16215767/102011601-35ba3200-3d13-11eb-926c-454f8e308f3e.png">

**Comment by psb1558** [comment]
The code-points above are for variants of upper- and lowercase letters.

Remaining categories of glyphs are: ligatures, small caps, numbers, punctuation, combining marks, mirrored runes. If there are any non-MUFI variants in the punctuation category, I'll encode those, but I'm not minded to encode the others.

**Comment by psb1558** [comment]
I think this will be the complete collection. Rearranged to keep upper/lowercase pairs together.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/16215767/102039223-31375d00-3d97-11eb-8211-3043b13bb8f2.png">

**Comment by jsbien** [comment]
Looks like you haven't uploaded it yet. 
I mentioned already in #44 that I'm unable to display most of them neither in Emacs nor in vim. This is quite a mystery, [fc-search-codepoint](https://unix.stackexchange.com/questions/162305/find-the-best-font-for-rendering-a-codepoint) confirms the characters are in the font. I still can display 0xF0000-0xF0003. Any ideas?

**Comment by psb1558** [comment]
The font with code points U+F0000-U+F001D is now up. The code points have changed (for example, what was U+F0009 is now U+F000F), so be sure to get rid of all old copies. Especially delete those files with "subset" in the name and run fc-cache on your font directory.

I don't think the code points will change now, so the font should be safe to use.

**Comment by jsbien** [comment]
Thanks!
I still have strange problems with displaying the characters in Emacs and vim, moreover vim displayes different characters than Emacs. Perhaps a Debian specific problem? I will look at it carefully and let you know about the result in a day or two.

**Comment by psb1558** [comment]
I wouldn't expect Emacs or vim to cache the fonts, but I can't think of what else could be happening besides different versions tripping over each other. (Emacs appears to have a clear-font-cache and/or clear-face-cache command.) For the system, make sure old copies are deleted, and run fc-cache to flush the font cache. Quit and restart Emacs. Maybe even restart the computer.

**Comment by jsbien** [comment]
It works in XeLaTeX as expected. I will investigate Emacs problem without haste.

**Comment by psb1558** [comment]
A font cache problem, then. I'm glad it's fixed.

**Comment by psb1558** [comment]
The current collection:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/16215767/102340534-a86e1c00-3f64-11eb-8c14-efc35c65b76a.png">
