### ISSUE TITLE
LATIN SMALL LETTER E WITH STROKE missing

### ISSUE THREAD

**Issue by jsbien** [psb1558/Junicode-New#48]
Just noticed when typesetting my paper.

**Comment by psb1558** [comment]
Do you mean U+0247? I don't have either that or U+0246, but glad to add them:
<img width="55" alt="image" src="https://user-images.githubusercontent.com/16215767/102353501-23d8c900-3f77-11eb-99e6-3fe1ba88466a.png">

**Comment by jsbien** [comment]
Yes, thanks in advance.

**Comment by jsbien** [comment]
That's not a real need, just a slight inconvenience, but I would appreciate adding also LATIN SMALL/CAPITAL LETTER A WITH STROKE.

**Comment by jsbien** [comment]
Sorry, I've confused fonts.

**Comment by psb1558** [comment]
No problem. I noticed just now that I hadn't added a small cap version of e + stroke. I've fixed that now.
