### ISSUE TITLE
Font license should be in repository.

### ISSUE THREAD

**Issue by afarlie** [psb1558/Junicode-New#5]
Hi,

In respect of getting JuniusX adopted on Wikimedia, could you indicate the font license in the repository? ( I've seen various references to Open Font License. on other versions of Junicode), 

Thanks.

( Cross reference to Wikimedia Phabricator ticket - https://phabricator.wikimedia.org/T253006)

**Comment by psb1558** [comment]
Thanks for the reminder. This is done now.
