### ISSUE TITLE
Tilde `~` is not too evident

### ISSUE THREAD

**Issue by sakkamade** [psb1558/Junicode-New#54]
In my opinion it is rather difficult to discern the tilde.
Example:
![tilde2](https://user-images.githubusercontent.com/62730422/117522417-c800f200-afa2-11eb-8a1d-b8955aefe6e3.png)![tilde](https://user-images.githubusercontent.com/62730422/117522390-9720bd00-afa2-11eb-8646-658679eaa490.png)

**Comment by psb1558** [comment]
I'm not sure how I came up with that shape for the tilde--it was a long time ago. I've compared the tilde in several fonts I admire, and they all have sharper curves. I'll work on this.

**Comment by psb1558** [comment]
Usually the asciitilde is larger too. Here's an experiment. Old:
<img width="110" alt="image" src="https://user-images.githubusercontent.com/16215767/117536867-8afd2580-afcb-11eb-8d98-1e522100c6b1.png">
New (rough):
<img width="159" alt="image" src="https://user-images.githubusercontent.com/16215767/117536877-96505100-afcb-11eb-95fd-1b3d3e981a02.png">

**Comment by psb1558** [comment]
All masters:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/16215767/117539035-9dc92780-afd6-11eb-93ac-a04da66abb19.png">

**Comment by sakkamade** [comment]
I have no profound knowledge in this scope, but to me it looks nice!

**Comment by sakkamade** [comment]
Oh! It's already in version 1.009!!???
Thank you!

**Comment by psb1558** [comment]
I'm trying to rememberto post a new version every week or so.
