### ISSUE TITLE
Exclamation and Question marks after `f`

### ISSUE THREAD

**Issue by sakkamade** [psb1558/Junicode-New#55]
Although this is the problem of many typefaces, 
I would still like to point it out in hopes that it will be amended to some extent.
If it is actually required of course.

Example:
![juni-typeface](https://user-images.githubusercontent.com/62730422/119203739-52595380-ba83-11eb-8f16-960c25c9d580.png)

**Comment by sakkamade** [comment]
Its look with "ss18":

![image](https://user-images.githubusercontent.com/62730422/119205204-2344e100-ba87-11eb-9057-894d52c20071.png)

**Comment by epilys** [comment]
<details><summary>Other pairs too: (Click here for some large screenshots)</summary>

![Screenshot_2021-05-22_02-20-22](https://user-images.githubusercontent.com/8278356/119206707-a0328380-baa4-11eb-9a5d-93627b654cb4.png)
![Screenshot_2021-05-22_02-21-36](https://user-images.githubusercontent.com/8278356/119206714-a3c60a80-baa4-11eb-81eb-c5208017b09d.png)
</details>

I have a `XeLaTeX` file that generates kerning pairs [from this website](http://www.as8.it/type/basic_kerning_text.html) if you want to try it:

https://gist.github.com/epilys/e150cfc61bb7b34d55eabb9cb0340c33

**Comment by sakkamade** [comment]
Thank you! but markdown is the only choice for me right now.

**Comment by psb1558** [comment]
Kerning for this font is a work in progress (and it may never be as complete as in a font that has a professional staff working on it), but f! and f? will be fixed in the next build, probably this weekend:
<img width="222" alt="image" src="https://user-images.githubusercontent.com/16215767/119211878-df4fdd00-ba82-11eb-9650-f2e0017c8dfd.png">

**Comment by sakkamade** [comment]
> and it may never be as complete as in a font that has a professional staff working on it

Oh my, oh my~ You don't have to be so modest. 
You have created amazing and cute-looking font, this much is clear.

As for the issue, even *Noto Serif* has it:
![image](https://user-images.githubusercontent.com/62730422/119215274-3a51f600-babc-11eb-9e96-0759ed4f1f96.png)

Even with some `script=latin rev=1` from Google on [fonts.google.com](https://fonts.google.com/specimen/Noto+Serif?preview.text=Staff%3F&preview.text_type=custom&query=noto+serif):
![image](https://user-images.githubusercontent.com/62730422/119215392-de3ba180-babc-11eb-819b-9007b1a71341.png)

Together with free version of _Times New Roman_ from [sourceforge.net](https://downloads.sourceforge.net/project/corefonts/the%20fonts/final/times32.exe):
![image](https://user-images.githubusercontent.com/62730422/119215451-49857380-babd-11eb-9f2e-95af2c7184a1.png)

**Comment by psb1558** [comment]
Interesting who kerns these pairs and who doesn't. What's with Monotype?
<img width="536" alt="image" src="https://user-images.githubusercontent.com/16215767/119223150-cf0d2180-bac5-11eb-90bb-15c103143f8f.png">

**Comment by psb1558** [comment]
This done now.
