### ISSUE TITLE
v1.010 - Regular - uni02F8 Modifier Letter Raised Colon interpolation issue

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-New#57]
v1.010 - Regular - uni02F8 Modifier Letter Raised Colon interpolation issue

First, it appears the element order is different between masters.
See: demo below

Second, it appears the actual glyphs for each weight are switched
- Light glyph is in Regular master
- Regular glyph is in Bold master
- Bold glyph is in Light master

Weight

![uni02F8 - v1 010 -2021-05-27_9-40-28](https://user-images.githubusercontent.com/844920/119868800-5e567280-bed4-11eb-8158-fe2938cbe5fd.gif)

**Comment by psb1558** [comment]
Thanks. Looks like it never got edited after being moved over from old Junicode. Fixed now.
