### ISSUE TITLE
v1.010 - Regular - uni01C1 Latin Letter Lateral Click interpolation issues

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-New#58]
v1.010 - Regular - uni01C1 Latin Letter Lateral Click interpolation issues

Appears there is an issue with the elements order.
Affects both the Weight and Width axes.

Width

![uni01C1 - Regular - Width - 2021-05-27_10-03-35](https://user-images.githubusercontent.com/844920/119869056-a83f5880-bed4-11eb-91fb-f71c116db86c.gif)

Weight

![uni01C1 - Regular - Weight - 2021-05-27_10-01-09](https://user-images.githubusercontent.com/844920/119869081-af666680-bed4-11eb-8ea5-f4df615ac9be.gif)

**Comment by psb1558** [comment]
Thanks—it's fixed now.
