### ISSUE TITLE
Issues with oldstyle left double quote

### ISSUE THREAD

**Issue by marrus-sh** [psb1558/Junicode-New#6]
U+201C “ LEFT DOUBLE QUOTATION MARK has an incorrect shape when using ss18 for weights other than Regular. All other quotation marks appear fine.

<img width="101" alt="image" src="https://user-images.githubusercontent.com/3212430/82399882-ec1e9880-9a0a-11ea-9f76-7cc2a6a43e3a.png">

**Comment by psb1558** [comment]
Components out of order--fixed now.

Thanks for the catch!
