### ISSUE TITLE
F200  LATIN SMALL LETTER A INSULAR FORM

### ISSUE THREAD

**Issue by jsbien** [psb1558/Junicode-New#60]
The shape is different from that on the MUFI site (https://mufi.info/m.php?p=mufichars&i=2&v=F2). Is this intentional?

**Comment by psb1558** [comment]
Absolutely. The pronounced lean of the rightmost stroke in Andron gives the impression that that is an essential feature of the insular **a**. But actually, as you can see in this quick-and-dirty sampler of insular **a**, it is optional. What's essential is that it is a one-storey **a**.
![insular_a_sampler](https://user-images.githubusercontent.com/16215767/125598670-92ad242a-e225-4787-aeb7-b6baeb0455e1.jpg)
Unlike that of Carolingian minuscule, with its ascender, which corresponds roughly to the upper storey of the **a** in a roman serif font like JuniusX.
<img width="62" alt="image" src="https://user-images.githubusercontent.com/16215767/125599169-e6fd36fa-00b5-4ef8-a1a9-5715f17e26bc.png">

**Comment by jsbien** [comment]
Looks like Carolingian minuscule would be useful for some Polish texts. 

> which corresponds roughly to the upper storey of the **a** in a roman serif font like JuniusX.

I'm not sure I understand, please elaborate.

**Comment by psb1558** [comment]
MUFI doesn't have a specifically Carolingian **a**. I'm guessing (but I don't really know) that they thought either that the ordinary roman **a** in fonts like Andron and Junicode was a close enough approximation or that there were no variations worth representing in Car. minuscule MSS. To my eye, though, the MUFI form at F214 labeled "uncial" is a pretty decent representation of a Car. minusucule. **a**:
<img width="131" alt="image" src="https://user-images.githubusercontent.com/16215767/125618356-37f8e7e3-6dee-40d9-aa76-b41b5fe66631.png">

**Comment by jsbien** [comment]
Thanks. I think F214 will do for my present purpose.
