### ISSUE TITLE
Inclusion of cased Glottal Stop

### ISSUE THREAD

**Issue by ind-nt** [psb1558/Junicode-New#61]
Peter, Junicode is a beautiful font. I would love to use it as a standard for Indigenous Languages in the Northwest Territories as the combining diacritical marks placements are some of the most accurate I've seen. For example, Ę̈́ which occurs in Chipewyan, needs quite a lot of height clearance works perfectly.

The only thing missing are the cased glottal stops at 0241 and 0242. Can these be placed in your work plan?

Cheers,
- Rajiv

**Comment by psb1558** [comment]
Before going to work on the other masters I thought I'd post these (here posing with other Upper/lowercase letters for comparison. Comment?
<img width="462" alt="image" src="https://user-images.githubusercontent.com/16215767/126709255-4b0b0a46-47e0-44c7-b066-8117a4f7df93.png">

**Comment by ind-nt** [comment]
Both cases look good. I like how you kept the serif consistent with the other capitals as opposed to 0294 which is consistent with the IPA set.

Thanks!

**Comment by psb1558** [comment]
Do these letters ever take diacritics?

**Comment by ind-nt** [comment]
They don't, they are used as is like here: https://www.pc.gc.ca/en/lhn-nhs/nt/saoyuehdacho

**Comment by psb1558** [comment]
Okay. Thanks for the link to the Saoyú-ʔehdacho National Historic Park. After I was done admiring the glottal stop characters, I read the description of the park. Amazing place. I read to my hiking-enthusiast wife the bit about how rescue teams might take a week to get to you if you have an emergency, and now she wants to go.

**Comment by psb1558** [comment]
Roman masters, order regular, bold, light, narrow, expanded. Lowercase:
<img width="289" alt="image" src="https://user-images.githubusercontent.com/16215767/126722160-b5c274bf-fe77-48d9-a0ae-f4ceb727db2e.png">

Uppercase:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/16215767/126722287-676f4177-dc61-49e3-bd8f-b23a5058196e.png">

**Comment by psb1558** [comment]
Italic masters
<img width="268" alt="image" src="https://user-images.githubusercontent.com/16215767/126734077-036f0aef-6329-424c-aa33-f1972edfc3ad.png">

<img width="403" alt="image" src="https://user-images.githubusercontent.com/16215767/126734133-77701a96-c9ac-4cdf-b0c5-748561fffef7.png">

**Comment by ind-nt** [comment]
That's great! Funny thing about the name of the park is that when it was officially launched in 2009 with the first federal sign posted, the text used the old non-unicode font that was commonly used in the territory in the 90s and 2000s. That font substituted characters in the upper 128-255 range with combined vowel forms as well as the glottal stop. The sign thus read Saoyu-Æehdacho instead of Saoyú-Ɂehdacho. Sometimes this issue still crops up as the older generation of translators still use that font. I built a unicode converter in 2013 for it.

**Comment by ind-nt** [comment]
Also, the Northwest Territories is a great place to travel, although quite expensive due to the fly in nature of the more amazing places like the Nahanni (Nahɂą Dehé) or Canol Trail. However, along with Greenland, we had the lowest incidence of Covid in the world outside of South Pacific islands throughout the pandemic.

**Comment by psb1558** [comment]
The pictures I've seen of the area are fantastic.

I've committed the source now, and a trial build of the roman ttf fonts (but not the italic or variable font, yet). I've done only rudimentary work on the spacing of these glottal stop characters. I would appreciate it if you could either (1) set some familiar text in JuniusX and scan it, looking for problems (collisions or letters too close / too far apart), or (2) send me a couple of paragraphs or a selection of sentences containing these characters so I can see the environments in which they typically occur. A text of about 300 words will do, if it's well chosen.
