### ISSUE TITLE
Tie bar height

### ISSUE THREAD

**Issue by Linguistx** [psb1558/Junicode-New#62]
Hi, first off, love the font! I've been compiling fonts that support all International Phonetic Alphabet fonts on this webpage - https://www.vulgarlang.com/ipafonts/

I noticed that in JuniusX the tie bar isn't as high as in the original Junicode in examples like: d͡z d͡ʑ d͡ʒ. Seems like the tie bar should hover above the ascenders, but in JuniusX it overlaps.

Keep up the great work!

**Comment by psb1558** [comment]
An oversight that has got to be fixed. Thanks for pointing it out.

**Comment by psb1558** [comment]
I've found the code that raises the tie (and other double diacritics) over, and it *seems* to be working, but I'll have to do more testing before I upload the new version.
<img width="191" alt="image" src="https://user-images.githubusercontent.com/16215767/126065763-06fb73b9-ada5-4c75-8583-985decb25885.png">

**Comment by psb1558** [comment]
Updated fonts now posted. Let me know if there's a problem.

**Comment by Linguistx** [comment]
That seems to have done the trick! Thanks
