### ISSUE TITLE
Width of narrow nonbreaking space?

### ISSUE THREAD

**Issue by marrus-sh** [psb1558/Junicode-New#7]
In both Junicode and JuniusX, U+202F NARROW NO-BREAK SPACE appears to have the same width as an ordinary space:

<img width="407" alt="image" src="https://user-images.githubusercontent.com/3212430/82400742-ec1f9800-9a0c-11ea-9967-7ae41bdb310d.png">

However, this character—used in a number of European languages (most notably French) to provide spacing around punctuation (and as a thousands separator)—typically has a width comparable to a thin space. Is there a reason Junicode makes it wider?

**Comment by psb1558** [comment]
Carelessness, I suspect. Gentium has U+202F at about 78% of the width of space, Brill at about 84%. I'm trying out 80%. I'll put up newly a newly generated version of JuniusX tomorrow afternoon (Eastern Time). Let me know if it doesn't look good.
